### ISSUE TITLE
Is it client or server

### ISSUE THREAD

**Issue by mugman174** [vimcord/vimcord.py#2]
Its the client, right?

**Comment by MoltenCoreDev** [comment]
it's yo mamas pussy

**Comment by mugman174** [comment]
`ok`

**Comment by DanKGooGLy** [comment]
Gosh diddly darn it sweetie can you please not swear on the Git Hub, it's rude and embarrasing

**Comment by kreat0** [comment]
i'd *whispers to self* just *whispers to self* wike *screams* t-to intewject fow a moment.  What you'we wefewwing t-to as sewvew,
is in fact, GNyU/sewvew, ow (・`ω´・) as I've wecentwy *looks at you* taken t-to cawwing it, GNyU p-pwus sewvew.
sewvew is nyot an sewvew unto itsewf, but wathew anyothew *screams* fwee componyent
of *screams* a fuwwy functionying GNyU system made usefuw by the x3 GNyU cowewibs, s-sheww
utiwities and vitaw system componyents compwising a fuww O-OS as definyed ÚwÚ by POSIX.

Many computew *screams* usews wun a modified vewsion of the x3 GNyU system evewy day,
without weawizing ;;w;; it. >w<  Thwough a p-pecuwiaw tuwn of events, the x3 vewsion of GNyU
which *sees bulge* is widewy used today is often cawwed *looks at you* "sewvew", and many of its usews awe
nyot awawe that i-it is basicawwy *huggles tightly* the x3 GNyU system, devewoped by the x3 GNyU Pwoject.

Thewe weawwy x3 is a sewvew, and these peopwe awe u-using it, but i-it is just *whispers to self* a
pawt of the x3 system they use. *walks away*  sewvew is the x3 software: x3 the x3 pwogwam in the x3 s-system
that awwocates *huggles tightly* the x3 machinye's wesouwces t-to the x3 othew pwogwams that you wun.
The softwawe is an essentiaw pawt of an opewating system, but usewess by itsewf;
it c-can onwy function in the x3 context *huggles tightly* of a compwete opewating system.  sewvew is
nyowmawwy used in combinyation with the x3 GNyU opewating system: the x3 whowe system
is UwU basicawwy *huggles tightly* GNyU with sewvew added, ow (・`ω´・) GNyU/sewvew.  Aww >w< the x3 so-cawwed "-"sewvew"
distwibutions awe weawwy x3 d-distwibutions of GNyU/sewvew.

**Comment by kreat0** [comment]
> Gosh diddly darn it sweetie can you please not swear on the Git Hub, it's rude and embarrasing

Annen azap çekecek.
